---
title: "04 - Accessibility-Calculations-Nick"
output: html_document
date: "2023-06-15"
---

```{r}
library(sf)
library(tmap)
library(dplyr)
library(accessibility)
```

```{r}
setwd("/Users/nicholas/Downloads/Care-Destinations")
```


```{r}
# ran into an issue with the travel time matrix - changing observations to match the example from package 

ttm_car$to_id <- as.character(ttm_car$to_id)
ttm_car$from_id <- as.character(ttm_car$to_id)
ttm_car$travel_time_p50 <- as.numeric((ttm_car$travel_time_p50))
save("ttm_car", file = "data-tt/ttm_car.RDS")

ttm_transit$to_id <- as.character(ttm_transit$to_id)
ttm_transit$from_id <- as.character(ttm_transit$to_id)
ttm_transit$travel_time_p50 <- as.numeric((ttm_transit$travel_time_p50))
save("ttm_transit", file = "data-tt/ttm_transit.RDS")

ttm_walk$to_id <- as.character(ttm_walk$to_id)
ttm_walk$from_id <- as.character(ttm_walk$to_id)
ttm_walk$travel_time_p50 <- as.numeric((ttm_walk$travel_time_p50))
save("ttm_walk", file = "data-tt/ttm_walk.RDS")

ttm_bike$to_id <- as.character(ttm_bike$to_id)
ttm_bike$from_id <- as.character(ttm_bike$to_id)
ttm_bike$travel_time_p50 <- as.numeric((ttm_bike$travel_time_p50))
save("ttm_bike", file = "data-tt/ttm_bike.RDS")


land_use_data$id <- as.character(land_use_data$id)
land_use_data$counts <- as.integer(land_use_data$counts)
land_use_data <- land_use_data %>% 
  st_as_sf() %>%
  sf::st_drop_geometry()
save("land_use_data", file = "data-tt/land_use_data.RDS")
```


```{r}
# required data: a travel matrix and some land use data - not loading properly as an RDS so being called in from environment 
# travel_matrix <- readRDS("data-tt/ttm_car.RDS")
# land_use_data <- readRDS("data-tt/land_use_data.RDS"))
travel_matrix <- ttm_car
land_use_data <- land_use_data
```

# Minimum Travel Cost by Car
```{r}
cost_closest <- cost_to_closest(
  travel_matrix,
  land_use_data,
  opportunity = "counts",
  travel_cost = "travel_time_p50",
  n = 1
)
head(cost_closest)
```

# Cumulative Cut-off by Car in 30 mins
```{r}
travel_matrix <- ttm_car

land_use_data <- land_use_data

cum_cutoff <- cumulative_cutoff(
  travel_matrix = travel_matrix, #name of the data.frame that contains the travel times and the from_ids to to_ids
  land_use_data = land_use_data, #name of the data.frame care-destination counts per DA
  opportunity = "counts", #name of the column for 'care destination' in 'land_use_data'
  travel_cost = "travel_time_p50",  #name of the travel_time column in 'travel_matrix'
  cutoff = 30 #play with this value to change the travel time cutoffs
)
head(cum_cutoff)
# Interpretation, each id can access X number of jobs within 45 minutes of travel. Population is not an input, so this is not a 'competitive' measure so this score is only based on impedance and nodes not consider the 'mass effect' (i.e., population centers that are larger demand more opportunities).
```


