---
title: "Geocoded Addresses Finalization"
output: html_document
date: "2023-05-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Counting blanks of the adjusted spreadsheet for reference 
```{r}
# Check if "LATITUDE" column has no text values
count <- sum(is.na(dest_test$LATITUDE) | is.null(dest_test$LATITUDE))

print(count)

# Check if "LATITUDE" column has text values
count <- length(dest_test$LATITUDE[!is.na(dest_test$LATITUDE) & !is.null(dest_test$LATITUDE)])

print(count)
```

# Continuing from Anastasia's example in the Qmd for consistency purposes then incorporating my adjustments to the dataset
```{r}
library(tidyverse)
library(tidygeocoder)
```

```{r}
dest <- read.csv("data-raw/Care_Destinations_2023.csv")
dest
```

```{r}
# Change cells in column Community to all be Hamilton
dest$Community <- ifelse(dest$Community != "", "Hamilton", dest$Community)
```

```{r}
# Join columns related to the address. First unit Address, Street_Name, and Street_Type with a space. And next unite the created F_Address with Community and Province separated by a comma and update the column to have the full address.
dest_test <- dest |>
  unite(F_Address, 
        Address, Street_Name, Street_Type,
        sep = " ") |>
  unite(F_Address, 
        F_Address, Community, Province,
        sep = ",")
```

```{r}
# Geocoding all the Addresses with Hamilton being the only community 
dest_geocoded <- dest_test |> 
  filter(is.na(LONGITUDE) & is.na(LATITUDE)) |> # only geocode dest data that is MISSING LONGTIDUE AND LATITUDE (this is 1,157 addresses)
  geocode(address = F_Address, method="osm")
```

```{r}
# Downloading Partially Geocoded Destinations to then be manually geocoded in Excel
write.csv(dest_geocoded, file = file.path("/Users/nicholas/Downloads", "Dest_Geocoded.csv"), row.names = FALSE)
```

```{r}
# Downloading the combined addresses into a .csv to be combined with the completed geocoded addresses
write.csv(dest_test, file = file.path("/Users/nicholas/Downloads", "Care_Destinations_tobecombined.csv"), row.names = FALSE)
```

