---
title: "Hamilton Map"
output: html_document
date: "2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
install.packages("tidytransit")
```

```{r}
library(tmap)
library(sf)
library(tidytransit)
library(dplyr)
library(stplanr)
```
#COMMUNITY SHAPES
```{r}
hamilton_communities <- st_read("/Users/nicholas/Downloads/Community_Boundaries/Community_Boundaries.shp")

hamilton_communities <- hamilton_communities %>%
  mutate(COMMUNITY_ = ifelse(COMMUNITY_ == "Hamilton", "Hamilton-Central", COMMUNITY_))
```


```{r}
# Plot the map with different colors for each community and the transit lines layer
Hamilton_Boundaries <- tm_shape(hamilton_communities) +
  tm_scale_bar(position = c("right", "bottom"), breaks = c(0, 1, 2, 4)) +
  tm_compass(position = c("left", "top"), size = 1.0) +
  tm_borders(lwd = 1, col = "black") +
  tm_text(text = "COMMUNITY_", size = 1) +
  tm_layout(title = "Hamilton Communities", title.size = 2, title.position = c('right', 'top')) 
tmap_save(Hamilton_Boundaries, filename = "/Users/nicholas/Downloads/Hamilton_Boundaries.png")
```

